### ISSUE TITLE
Don't restart if proxy request returns 404

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-publish#75]
**Description**
If a proxy request fails with status `404` the currently generated VCL triggers a `RESTART` for fallback static handling. The `404` should be delivered instead. 

Stripped down `helix-config.yaml` demonstrating the issue:

```yaml
version: 1
definitions:
  defaults:
    # Run default content from github repo
    - &defaultRepo https://github.com/adobe/developer.adobe.com.git#master
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
    proxy:
      &proxystrain
      origin: https://www.adobe.io/

strains:
  - name: default
    <<: *basestrain

  - name: xd-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
  - name: staging
    <<: *proxystrain
    url: https://adobedevsite.helix-demo.xyz/
```

A request to `https://adobedevsite.helix-demo.xyz/homepage.css` is matched by the `staging` proxy strain via `url` property. 

In local dev environment a `404` is returned  (expected since `https://www.adobe.io/homepage.css` is not found). 

On Fastly however the request succeeds since the `RESTART` wrongly triggers static fallback resolution.

**Expected behavior**
Failing proxy requests should not be restarted.

**Version:**
`hlx 1.0.0`
